### ISSUE TITLE
getComputedStyle returns null for iframes in Firefox 

### ISSUE THREAD

**Issue by debreczeniandras** [deepblue-networks/toolkit#3]
Here:
https://github.com/deepblue-networks/toolkit/blob/94ca0ff5f8beba340ca88a72381beecff1d723af/src/services/viewport.service.js#L97

See bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=548397

See a possible solution for another library:
https://github.com/marcj/css-element-queries/issues/148

**Comment by dareksob** [comment]
already integrate this fix
